services:
  postgres:
    image: postgres:15-alpine
    container_name: pulltabs-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: pulltabs-server
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: pulltabs
      DB_USER: pulltabs_user
      DB_PASSWORD: pulltabs_password
      JWT_SECRET: docker_dev_jwt_secret_key_min_32_characters
      JWT_EXPIRES_IN: 24h
      CLIENT_URL: http://localhost:5173
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:
